-- ============================================================
-- Effyra – Rollenprüfung Kindercodes: INHALT NACH supabase-kids.sql VERSCHOBEN.
-- ============================================================
-- ⚠️ Diese Datei definierte create_child_code und revoke_child_code ein ZWEITES
--    Mal. Sie stand in RUNBOOK.md als LETZTER Schritt (19) und gewann damit
--    gegen supabase-kids.sql (Schritt 6) – und ihre Fassung von
--    create_child_code fügt OHNE expires_at ein. Nach einem vollständigen
--    Durchlauf der Reihenfolge waren die Kindercodes deshalb wieder unbefristet:
--    join_as_child lässt `expires_at is null` ausdrücklich zu, die 14-Tage-Frist
--    aus kids.sql war wirkungslos. Beide Dateien hatten je eine Hälfte des
--    richtigen Codes – die Rollenprüfung hier, die Ablauffrist dort.
--    → Die EINE gültige Definition steht jetzt in **supabase-kids.sql**
--      (Abschnitte 3 und 4), mit Rollenprüfung UND Ablauffrist.
--    Diese Datei wird nicht mehr ausgeführt und bleibt nur als Beleg stehen.
--    Gleiche Bereinigung wie zuvor bei consume_ai, save_family und get_entitlements.
-- ============================================================
